name: Lay
version: '${project.version}'
main: net.layin.lay.Lay
api-version: '1.20'
author: Layin Studio
website: https://afdian.net/a/layiner
commands:
  login:
    description: 登录
    usage: /login <密码>
  register:
    description: 注册
    usage: /register <密码> <重复密码>
  menu:
    description: 打开菜单
    usage: /menu
  tpa:
    description: 玩家间传送
    usage: |
      /tpa <玩家昵称> 可以向玩家发送传送请求
      /tpa accept 可以接受玩家的传送请求
      /tpa deny 可以拒绝玩家的传送请求
  shop:
    description: 打开商店
    usage: |
      /shop 玩家可操作打开商店进行交易
      /shop add <售价> 管理员可操作添加商品
      /shop set <商品编号> <现售价> 管理员可操作更改商品
  land:
    description: 地皮相关操作
    usage: |
      /land create <地皮名称> 创建一个地皮并命名
      /land delete <地皮名称> 删除属于自己的名为<地皮名称>的地皮
      /land setPermissions <地皮名称> permissions player true/false 设置player在<地皮名称>地皮的permission权限
      /land askPermissions <地皮名称> permissions 向<地皮名称>地皮的主人要求permission权限
      /land goto <地皮名称> 去往<地皮名称>的中心,需要EnterPermission权限
  vip:
    description: 设置VIP等级
    usage: /vip set <用户名> <类别> 仅管理员可操作
  config:
    description: 保存或加载配置文件，用于调试